### ISSUE TITLE
'main' function in before_deploy.sh never called?

### ISSUE THREAD

**Issue by BakaBBQ** [japaric/rust-everywhere#30]
I noticed this when trying out this awesome project. I double-checked, and I feel that the 'main' function in before_deploy.sh is never called. I have no experience in shell programming; therefore it could be a mistake on my side. But can you double check?

In install.sh you see there is `main` called in the last line. There is no `main` call in before_deploy.sh.

**Comment by japaric** [comment]
Whoops! Thanks for the heads up, it got lost during the refactor.
