### ISSUE TITLE
Use cargo cache

### ISSUE THREAD

**Issue by dns2utf8** [japaric/rust-everywhere#45]
Is it possible with this setup to use the cargo caching?
http://docs.travis-ci.com/user/caching/

**Comment by japaric** [comment]
We don't use `languages: rust` so `cache: cargo` won't Just Work, but I do think is possible to enable cargo caching (by manually specifying the directories to cache). I'd have to look into it.

**Comment by japaric** [comment]
done in #47

**Comment by dns2utf8** [comment]
Thank you
