### ISSUE TITLE
mention support for annotated tags

### ISSUE THREAD

**Issue by BurntSushi** [japaric/rust-everywhere#52]
With the current AppVeyor setup, I learned the hard way that it only seems to support lightweight tags in git, so that if you push an annotated tag, AppVeyor emits this enormously helpful error message:

```
Skip "GitHub" deployment as environment variable has not matched ("appveyor_repo_tag" is "false", should be "true")
```

(This config option was set to `true`, and indeed, is so in your template.)

In order to support annotated tags, [you need to add an explicit filter in the `branches` section of the `appveyor.yml` file](http://help.appveyor.com/discussions/problems/3483-github-tag-push-doesnt-trigger-build#comment_38384095). e.g.,

```
branches:
  only:
    - /v\d+\.\d+\.\d+/
  except:
    - master
    - develop
```

Once I did this, AppVeyor picked up my annotated tags. (Which Travis also does with your setup out of the box.)

@japaric Would you accept a PR that added a little note in the comments of your `appveyor.yml` template? It would have saved me about 30 minutes of flailing. :-) (Very nice work by the way, because in sum, your work saved me several _days_ of flailing!)

**Comment by japaric** [comment]
> It would have saved me about 30 minutes of flailing. :-)

Ouch.

> Would you accept a PR that added a little note in the comments of your appveyor.yml template?

Sure. You might as well add the tag regex to "branches.only". We already have a similar regex on the [.travis.yml](https://github.com/japaric/rust-everywhere/blob/687a355ae1833560020159c9878aa5d9375d4292/.travis.yml#L196-L198).

> Very nice work by the way, because in sum, your work saved me several days of flailing!

Happy to hear that! :smile:
